<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(["register"=>false]);

// AQUI COMIENZA SERVICIOS ESCOLARES

Route::get('/escolares', 'EscolaresController@index')
    ->name('inicio_escolares')
    ->middleware('auth','role:escolares');
Route::get('/escolares/alumnos/consulta', 'EscolaresController@buscar')
    ->middleware('auth','role:escolares');
Route::get('/escolares/alumnos/alta', 'EscolaresController@nuevo')
    ->middleware('auth','role:escolares');
Route::post('/escolares/alumnos/nuevo','EscolaresController@altanuevo')
    ->name('escolares.nuevo_alumno')
    ->middleware('auth','role:escolares');
Route::get('/escolares/periodos/alta','EscolaresController@periodos')
    ->middleware('auth','role:escolares');
Route::post('/escolares/periodos/nuevo','EscolaresController@periodoalta')
    ->name('escolares.periodo_nuevo')
    ->middleware('auth','role:escolares');
Route::get('/escolares/periodos/modifica','EscolaresController@periodomodifica')
    ->middleware('auth','role:escolares');
Route::post('/escolares/periodos/modificar','EscolaresController@periodomodificar')
    ->name('escolares.periodo_mod1')
    ->middleware('auth','role:escolares');
Route::post('/escolares/periodo/modificado','EscolaresController@periodoupdate')
    ->name('escolares.periodo_upd')
    ->middleware('auth','role:escolares');
Route::get('/escolares/actas','EscolaresController@periodoactas1')
    ->middleware('auth','role:escolares');
Route::post('/escolares/periodo/actas2','EscolaresController@periodoactas2')
    ->name('escolares.actas2')
    ->middleware('auth','role:escolares');
Route::post('/escolares/periodo/actas3','EscolaresController@periodoactas3')
    ->name('escolares.actas3')
    ->middleware('auth','role:escolares');
Route::get('/escolares/acta/modificar/{periodo}/{rfc}/{materia}/{grupo}','EscolaresController@modificaracta')
    ->middleware('auth','role:escolares');
Route::get('/escolares/acta/imprimir/{periodo}/{rfc}/{materia}/{grupo}','EscolaresController@imprimiracta')
    ->middleware('auth','role:escolares');
Route::post('/escolares/periodo/actasupdate','EscolaresController@actasupdate')
    ->name('escolares.actas_upd')
    ->middleware('auth','role:escolares');
Route::post('/escolares/buscar','EscolaresController@busqueda')
    ->name('escolares.buscar')
    ->middleware('auth','role:escolares');
Route::post('/escolares/acciones','EscolaresController@accion')
    ->name('escolares.accion')
    ->middleware('auth','role:escolares');
Route::post('/escolares/accionesk','EscolaresController@accionk')
    ->name('escolares.accion_kardex')
    ->middleware('auth','role:escolares');
Route::post('/escolares/accionesk_alta','EscolaresController@accionkalta')
    ->name('escolares.accion_kardex_alta')
    ->middleware('auth','role:escolares');
Route::post('/escolares/periodo_k','EscolaresController@accionkperiodo')
    ->name('escolares.accion_kardex_modificar1')
    ->middleware('auth','role:escolares');
Route::get('/escolares/modificar/{periodo}/{control}/{materia}','EscolaresController@modificarkardex')
    ->middleware('auth','role:escolares');
Route::get('/escolares/eliminar/{periodo}/{control}/{materia}','EscolaresController@eliminarkardex')
    ->middleware('auth','role:escolares');
Route::post('/escolares/imprimir_boleta','EscolaresController@imprimirboleta')
    ->name('escolares.imprimir boleta')
    ->middleware('auth','role:escolares');
Route::post('/escolares/actualizar/kardex','EscolaresController@kardexupdate')
    ->name('escolares.accion_actualiza_kardex')
    ->middleware('auth','role:escolares');
Route::post('/escolares/actualizar/estatus','EscolaresController@estatusupdate')
    ->name('escolares.accion_actualiza_estatus')
    ->middleware('auth','role:escolares');
Route::post('/escolares/actualizar/especialidad','EscolaresController@especialidadupdate')
    ->name('escolares.accion_actualiza_especialidad')
    ->middleware('auth','role:escolares');
Route::post('/escolares/actualizar/carrera','EscolaresController@carreraupdate')
    ->name('escolares.accion_actualiza_carrera')
    ->middleware('auth','role:escolares');
Route::post('/escolares/eliminar/','EscolaresController@alumnodelete')
    ->name('escolares.accion_borrar')
    ->middleware('auth','role:escolares');
Route::post('/escolares/baja/','EscolaresController@alumnobajatemp')
    ->name('escolares.accion_bajatemp')
    ->middleware('auth','role:escolares');
Route::post('/escolares/nss/','EscolaresController@alumnonss')
    ->name('escolares.nss')
    ->middleware('auth','role:escolares');
Route::get('/escolares/reinscripcion','EscolaresController@reinscripcion')
    ->middleware('auth','role:escolares');
Route::post('/escolares/reinscripcion/acciones','EscolaresController@accion_re')
    ->name('escolares.accion-reinscripcion')
    ->middleware('auth','role:escolares');
Route::post('/escolares/reinscripcion/alta_fechas','EscolaresController@altaf_re')
    ->name('escolares.fechas-reinscripcion')
    ->middleware('auth','role:escolares');
Route::get('/escolares/estadistica/prepoblacion','EscolaresController@prepoblacion')
    ->middleware('auth','role:escolares');
Route::post('/escolares/estadistica/poblacion','EscolaresController@poblacion')
    ->name('escolares.poblacion')
    ->middleware('auth','role:escolares');
Route::get('/escolares/estadistica/{periodo}/{carrera}/{reticula}','EscolaresController@pobxcarrera')
    ->name('escolares.est_carrera')
    ->middleware('auth','role:escolares');
Route::get('/escolares/contrasena','EscolaresController@contrasenia')
    ->middleware('auth','role:escolares');
Route::post('/escolares/ccontrasena','EscolaresController@ccontrasenia')
    ->name('escolares.contra')
    ->middleware('auth','role:escolares');
Route::post('/escolares/constancia','ConstanciaPDFController@crearPDF')
    ->name('escolares.constancia');
Route::get('/escolares/carreras/alta','EscolaresController@carrerasalta')
    ->middleware('auth','role:escolares');
Route::post('/escolares/carreras/alta_procesa','EscolaresController@carreranueva')
    ->name('escolares.carrera_alta')
    ->middleware('auth','role:escolares');
Route::get('/escolares/carreras/especialidades','EscolaresController@especialidadesalta')
    ->middleware('auth','role:escolares');
Route::get('/escolares/carreras/materias','EscolaresController@materianueva')
    ->middleware('auth','role:escolares');
Route::post('/escolares/especialidad/alta','EscolaresController@especialidadnueva')
    ->name('escolares.especialidad_alta')
    ->middleware('auth','role:escolares');
Route::post('/escolares/materias/accion','EscolaresController@materiasacciones')
    ->name('escolares.materias_acciones')
    ->middleware('auth','role:escolares');
Route::post('/escolares/materias/nueva','EscolaresController@materiaalta')
    ->name('escolares.materia_nueva')
    ->middleware('auth','role:escolares');
Route::post('/escolares/reticulas/vista','EscolaresController@vistareticula')
    ->name('escolares.vista_reticula')
    ->middleware('auth','role:escolares');
Route::post('/escolares/certificado','EscolaresController@certificado')
    ->name('escolares.certificado')
    ->middleware('auth','role:escolares');
Route::post('/escolares/idiomas','IdiomasPDFController@crearPDF')
    ->name('escolares.idiomas');
Route::post('/escolares/imprimir_certificado','CertificadoPDFController@crearPDF')
    ->name('escolares.certificado_pdf');
Route::get('/escolares/actas/registro','EscolaresController@periodoactas_m1')
    ->middleware('auth','role:escolares');
Route::post('/escolares/periodo/registro2','EscolaresController@periodoactas_m2')
    ->name('escolares.registro2')
    ->middleware('auth','role:escolares');
Route::post('/escolares/periodo/registro3','EscolaresController@periodoactas_m3')
    ->name('escolares.registro3')
    ->middleware('auth','role:escolares');
Route::post('/escolares/periodo/registro4','EscolaresController@periodoactas_m4')
    ->name('escolares.registro4')
    ->middleware('auth','role:escolares');
Route::get('/escolares/actas/mantenimiento','EscolaresController@actas_mantenimiento')
    ->middleware('auth','role:escolares');
Route::post('/escolares/actas/consulta_estatus','EscolaresController@actas_estatus')
    ->name('escolares.actas_estatus')
    ->middleware('auth','role:escolares');
Route::get('/escolares/cierre','EscolaresController@cierre')
    ->middleware('auth','role:escolares');
Route::post('/escolares/cerrar_periodo','EscolaresController@cierre_accion')
    ->name('escolares.cierre_semestre')
    ->middleware('auth','role:escolares');
Route::get('/escolares/idiomas/liberacion','EscolaresController@idiomas_lib1')
    ->middleware('auth','role:escolares');
Route::post('/escolares/idiomas/liberar','EscolaresController@idiomas_lib2')
    ->name('escolares.liberar_idioma')
    ->middleware('auth','role:escolares');
Route::post('/escolares/idiomas/liberar2','EscolaresController@idiomas_lib3')
    ->name('escolares.liberar_idioma2')
    ->middleware('auth','role:escolares');
Route::get('/escolares/idiomas/impresion','EscolaresController@idiomas_impre')
    ->middleware('auth','role:escolares');
Route::post('/escolares/idiomas/imprimir2','EscolaresController@idiomas_impre2')
    ->name('escolares.imprimir_idioma')
    ->middleware('auth','role:escolares');
//AQUI TERMINA SERVICIOS ESCOLARES

//AQUI COMIENZA ALUMNO
Route::get('/estudiante', 'AlumnosController@index')
    ->name('inicio_alumno')
    ->middleware('auth','role:alumno');
Route::get('/estudiante/kardex','AlumnosController@ver_kardex')
    ->middleware('auth','role:alumno');
Route::get('/estudiante/horario','AlumnosController@horario')
    ->middleware('auth','role:alumno');
Route::get('/estudiante/eval','AlumnosController@evaluacion')
    ->middleware('auth','role:alumno');
Route::post('/estudiante/evaluacion','AlumnosController@evaluar')
    ->name('eval_doc')
    ->middleware('auth','role:alumno');
Route::post('/estudiante/eval_doc','AlumnosController@evaluaciondoc')
    ->name('eval_docente')
    ->middleware('auth','role:alumno');
Route::get('/estudiante/boleta','AlumnosController@boleta')
    ->middleware('auth','role:alumno');
Route::post('/estudiante/boleta2','AlumnosController@verboleta')
    ->name('alumno_boleta')
    ->middleware('auth','role:alumno');
Route::get('/estudiante/reticula','AlumnosController@verreticula')
    ->middleware('auth','role:alumno');
Route::get('/estudiante/reinscripcion','AlumnosController@reinscripcion')
    ->middleware('auth','role:alumno');
Route::get('/estudiante/reinscripcion/{materia}/{tipocur}','AlumnosController@seleccion_materia')
    ->middleware('auth','role:alumno');
Route::get('/estudiante/calificaciones','AlumnosController@vercalificaciones')
    ->middleware('auth','role:alumno');
Route::post('/estudiante/seleccion/','AlumnosController@reinscribir')
    ->name('alumno.seleccion')
    ->middleware('auth','role:alumno');
Route::get('/estudiante/eliminar','AlumnosController@bajam')
    ->middleware('auth','role:alumno');
Route::post('/estudiante/seleccion/baja','AlumnosController@baja_materia')
    ->name('alumno.baja_m')
    ->middleware('auth','role:alumno');
Route::post('/estudiante/accionesk','AlumnosController@accionkardex')
    ->name('alumno.accion_kardex')
    ->middleware('auth','role:alumno');
//AQUI TERMINA ALUMNO

//AQUI COMIENZA DOCENTE
Route::get('/personal', 'PersonalController@index')
    ->name('inicio_personal')
    ->middleware('auth','role:docente');
Route::get('/personal/semestre','PersonalController@encurso')
    ->middleware('auth','role:docente');
Route::get('/personal/semestre/listas/{materia}/{gpo}','PersonalController@lista')
    ->middleware('auth','role:docente');
Route::get('/personal/semestre/excel/{materia}/{gpo}','PersonalController@excel')
    ->middleware('auth','role:docente');
Route::get('/personal/semestre/evaluar/{materia}/{gpo}','PersonalController@evaluar')
    ->middleware('auth','role:docente');
Route::post('/personal/semestre/calificaciones','PersonalController@calificar')
    ->name('personal_cal1')
    ->middleware('auth','role:docente');
Route::get('/personal/semestre/acta/{materia}/{gpo}','PersonalController@acta')
    ->middleware('auth','role:docente');
Route::get('/personal/contrasena','PersonalController@contrasenia')
    ->middleware('auth','role:docente');
Route::post('/personal/ccontrasena','PersonalController@ccontrasenia')
    ->name('personal_contra')
    ->middleware('auth','role:docente');
Route::get('/personal/residencias','PersonalController@residencias1')
    ->middleware('auth','role:docente');
Route::post('/personal/eval/residencias','PersonalController@residencias2')
    ->name('personal_residencias1')
    ->middleware('auth','role:docente');
Route::get('/personal/residencias/evaluar/{periodo}/{materia}/{gpo}/{control}','PersonalController@residenciaevaluar')
    ->middleware('auth','role:docente');
Route::post('/personal/residencias/calificar','PersonalController@residenciascalifica')
    ->name('personal_residencias2')
    ->middleware('auth','role:docente');
Route::get('/personal/residencias/acta/{periodo}/{materia}/{gpo}','PersonalController@actaresidencia')
    ->middleware('auth','role:docente');
//AQUI TERMINA DOCENTE

//AQUI COMIENZA DIVISION
Route::get('/dep', 'DivisionController@index')
    ->name('inicio_division')
    ->middleware('auth','role:division');
Route::get('/dep/alta/grupo','DivisionController@altagrupo')
    ->middleware('auth','role:division');
Route::post('/dep/alta/materias','DivisionController@listado2')
    ->name('dep_lista2')
    ->middleware('auth','role:division');
Route::get('/dep/grupos/alta/{periodo}/{materia}/{carrera}/{reticula}','DivisionController@creargrupo1')
    ->name('dep_alta_grupo')
    ->middleware('auth','role:division');
Route::post('/dep/alta/grupo','DivisionController@creargrupo2')
    ->name('dep_grupo_alta')
    ->middleware('auth','role:division');
Route::get('/dep/alta/paralelo','DivisionController@paralelo1')
    ->middleware('auth','role:division');
Route::post('/dep/alta/paralela2','DivisionController@paralelo2')
    ->name('dep_paralelo2')
    ->middleware('auth','role:division');
Route::post('/dep/alta/paralela3','DivisionController@paralelo3')
    ->name('dep_paralelo3')
    ->middleware('auth','role:division');
Route::get('/dep/existentes','DivisionController@existentes')
    ->middleware('auth','role:division');
Route::post('/dep/listado/','DivisionController@listado')
    ->name('dep_lista')
    ->middleware('auth','role:division');
Route::post('/dep/listado2/','DivisionController@listado2')
    ->name('dep_infogpo')
    ->middleware('auth','role:division');
Route::get('/dep/grupos/info/{periodo}/{materia}/{gpo}','DivisionController@info')
    ->name('dep_info')
    ->middleware('auth','role:division');
Route::post('/dep/acciones/','DivisionController@acciones')
    ->name('dep_acciones')
    ->middleware('auth','role:division');
Route::post('/dep/altaa/','DivisionController@altacontrol')
    ->name('dep_altaa')
    ->middleware('auth','role:division');
Route::delete('/dep/bajaa/','DivisionController@bajacontrol')
    ->name('dep_bajaa')
    ->middleware('auth','role:division');
Route::post('/dep/grupos/modificar/horario','DivisionController@updatehorario')
    ->name('dep_grupo_modifica')->middleware('auth','role:division');
Route::post('/dep/grupos/capacidad','DivisionController@capgrupo')
    ->name('dep_cap_grupo')
    ->middleware('auth','role:division');
Route::get('/dep/alumnos/consulta','DivisionController@buscar')
    ->middleware('auth','role:division');
Route::post('/dep/alumno/buscar','DivisionController@busqueda')
    ->name('dep.buscar')
    ->middleware('auth','role:division');
Route::post('/dep/alumno/datos','DivisionController@accion2')
    ->name('dep.accion2')
    ->middleware('auth','role:division');
Route::get('/dep/estadistica/prepoblacion','DivisionController@prepoblacion')
    ->middleware('auth','role:division');
Route::post('/dep/estadistica/poblacion','DivisionController@poblacion')
    ->name('dep_poblacion')
    ->middleware('auth','role:division');
Route::get('/dep/estadistica/{periodo}/{carrera}/{reticula}','DivisionController@pobxcarrera')
    ->name('dep_est_carrera')
    ->middleware('auth','role:division');
Route::get('/dep/estadistica/aulas','DivisionController@pobxaulas')
    ->middleware('auth','role:division');
Route::post('/dep/estadistico/aula2','DivisionController@pobxaulas2')
    ->name('dep_aula')
    ->middleware('auth','role:division');
Route::get('/dep/contrasena','DivisionController@contrasenia')
    ->middleware('auth','role:division');
Route::post('/dep/ccontrasena','DivisionController@ccontrasenia')
    ->name('division_contra')
    ->middleware('auth','role:division');
Route::get('/dep/alumnos/psemestre','DivisionController@psemestre')
    ->middleware('auth','role:division');
Route::post('/dep/alumnos/cambio_primer','DivisionController@psemestre2')
    ->name('division_cambio_primer')
    ->middleware('auth','role:division');
Route::post('/dep/alumnos/cambio_primer2','DivisionController@psemestrecambio')
    ->name('division_cambio_primer2')
    ->middleware('auth','role:division');
//En desuso
Route::post('/dep/altad/','DivisionController@altadocente')
    ->name('dep_altad')
    ->middleware('auth','role:division');
//AQUI TERMINA DIVISION

//AQUI COMIENZA ACADEMICOS
Route::get('/acad', 'AcademicosController@index')
    ->name('inicio_academicos')
    ->middleware('auth','role:acad');
Route::get('/acad/existentes','AcademicosController@existentes')
    ->middleware('auth','role:acad');
Route::post('/acad/listado/','AcademicosController@listado')
    ->name('acad_lista')
    ->middleware('auth','role:acad');
Route::get('/acad/grupos/info/{periodo}/{materia}/{gpo}','AcademicosController@info')
    ->name('acad_info')
    ->middleware('auth','role:acad');
Route::post('/acad/acciones/','AcademicosController@acciones')
    ->name('acad_acciones')
    ->middleware('auth','role:acad');
Route::post('/acad/altad/','AcademicosController@altadocente')
    ->name('acad_altad')
    ->middleware('auth','role:acad');
Route::get('/acad/estadistica/prepoblacion','AcademicosController@prepoblacion')
    ->middleware('auth','role:acad');
Route::post('/acad/estadistica/poblacion','AcademicosController@poblacion')
    ->name('acad_poblacion')
    ->middleware('auth','role:acad');
Route::get('/acad/estadistica/{periodo}/{carrera}/{reticula}','AcademicosController@pobxcarrera')
    ->name('acad_est_carrera')
    ->middleware('auth','role:acad');
Route::get('/acad/estadistica/aulas','AcademicosController@pobxaulas')
    ->middleware('auth','role:acad');
Route::post('/acad/estadistico/aula2','AcademicosController@pobxaulas2')
    ->name('acad_aula')
    ->middleware('auth','role:acad');
Route::get('/acad/estadistica/predocentes','AcademicosController@predocentes')
    ->middleware('auth','role:acad');
Route::post('/acad/estadistico/personal','AcademicosController@docente')
    ->name('acad_personal')
    ->middleware('auth','role:acad');
Route::get('/acad/horarios','AcademicosController@otroshorarios')
    ->middleware('auth','role:acad');
Route::post('/acad/horarios/accion','AcademicosController@otroshorariosaccion')
    ->name('acad_otrosh')
    ->middleware('auth','role:acad');
Route::post('/acad/horarios/alta_admin','AcademicosController@procesaadmvoalta')
    ->name('acad_altaadmin')
    ->middleware('auth','role:acad');
Route::get('/acad/modificar/admvo/{periodo}/{personal}/{numero}','AcademicosController@modificaadmvo')
    ->name('acad_modhadmin')
    ->middleware('auth','role:acad');
Route::get('/acad/eliminar/admvo/{periodo}/{personal}/{numero}','AcademicosController@eliminaadmvo')
    ->name('acad_delhadmin')
    ->middleware('auth','role:acad');
Route::post('/acad/actualizar/hadmvo','AcademicosController@procesoadmvoupdate')
    ->name('acad_modadmin')
    ->middleware('auth','role:acad');
Route::get('/acad/modificar/apoyo/{periodo}/{personal}/{numero}','AcademicosController@modificaapoyo')
    ->name('acad_modhapoyo')
    ->middleware('auth','role:acad');
Route::get('/acad/eliminar/apoyo/{periodo}/{personal}/{numero}','AcademicosController@eliminaapoyo')
    ->name('acad_delhapoyo')
    ->middleware('auth','role:acad');
Route::post('/acad/actualizar/hapoyo','AcademicosController@procesoapoyoupdate')
    ->name('acad_modapoyo')
    ->middleware('auth','role:acad');
Route::post('/acad/horarios/alta_apoyo','AcademicosController@procesaapoyoalta')
    ->name('acad_altaapoyo')
    ->middleware('auth','role:acad');
Route::post('/acad/horarios/alta_obs','AcademicosController@altaobservacion')
    ->name('acad_altaobs')
    ->middleware('auth','role:acad');
Route::get('/acad/modificar/obs/{periodo}/{personal}','AcademicosController@modificaobservaciones')
    ->name('acad_modobs')
    ->middleware('auth','role:acad');
Route::post('/acad/actualizar/observaciones','AcademicosController@observacionesupdate')
    ->name('acad_modobservaciones')
    ->middleware('auth','role:acad');
Route::get('/acad/eliminar/obs/{periodo}/{personal}','AcademicosController@eliminaobservaciones')
    ->name('acad_deloobs')
    ->middleware('auth','role:acad');
Route::get('/acad/contrasena','AcademicosController@contrasenia')
    ->middleware('auth','role:acad');
Route::post('/acad/ccontrasena','AcademicosController@ccontrasenia')
    ->name('acad_contra')
    ->middleware('auth','role:acad');
Route::post('/impresion/horario','HorarioPDFController@crearPDF')
    ->name('horario_ind');
Route::get('/acad/modificar','AcademicosController@cambiarcontra')
    ->middleware('auth','role:acad');
Route::post('/acad/modificar_contra','AcademicosController@cambiarcontra2')
    ->name('acad_cambiar_contra_doc');
Route::post('/acad/modificar_contra2','AcademicosController@cambiarcontra3')
    ->name('acad_cambiar_contra_doc2');
Route::get('/acad/reset','AcademicosController@actareset')
    ->middleware('auth','role:acad');
Route::post('/acad/reset_acta','AcademicosController@actareset2')
    ->name('acad_reset2');
Route::post('/acad/reset_acta2','AcademicosController@actareset3')
    ->name('acad_reset3');
//AQUI TERMINA ACADEMICOS


//AQUI COMIENZA COORD VERANO
Route::get('/verano', 'VeranoController@index')
    ->name('inicio_verano')
    ->middleware('auth','role:verano');
Route::get('/verano/existentes','VeranoController@existentes')
    ->middleware('auth','role:verano');
Route::get('/verano/alta/paralelo','VeranoController@paralelo1')
    ->middleware('auth','role:verano');
Route::post('/verano/listado/','VeranoController@listado')
    ->name('verano_lista')
    ->middleware('auth','role:verano');
Route::post('/verano/listado2/','VeranoController@listado2')
    ->name('verano_infogpo')
    ->middleware('auth','role:verano');
Route::get('/verano/grupos/info/{materia}/{gpo}','VeranoController@info')
    ->name('verano_info')
    ->middleware('auth','role:verano');
Route::post('/verano/acciones/','VeranoController@acciones')
    ->name('verano_acciones')
    ->middleware('auth','role:verano');
Route::post('/verano/altaa/','VeranoController@altacontrol')
    ->name('verano_altaa')
    ->middleware('auth','role:verano');
Route::delete('/verano/bajaa/','VeranoController@bajacontrol')
    ->name('verano_bajaa')
    ->middleware('auth','role:verano');
Route::post('/verano/altad/','VeranoController@altadocente')
    ->name('verano_altad')
    ->middleware('auth','role:verano');
Route::get('/verano/alta/grupo','VeranoController@altagrupo')
    ->middleware('auth','role:verano');
Route::post('/verano/alta/materias','VeranoController@listado2')
    ->name('verano_lista2')
    ->middleware('auth','role:verano');
Route::get('/verano/grupos/alta/{materia}/{carrera}/{reticula}','VeranoController@creargrupo1')
    ->name('verano_alta_grupo')
    ->middleware('auth','role:verano');
Route::post('/verano/alta/grupo','VeranoController@creargrupo2')
    ->name('verano_grupo_alta')
    ->middleware('auth','role:verano');
Route::post('/verano/alta/paralela2','VeranoController@paralelo2')
    ->name('verano_paralelo2')
    ->middleware('auth','role:verano');
Route::post('/verano/alta/paralela3','VeranoController@paralelo3')
    ->name('verano_paralelo3')
    ->middleware('auth','role:verano');
Route::get('/verano/modificar/grupo','VeranoController@modificar1')
    ->middleware('auth','role:verano');
Route::post('/verano/modificar/grupo2','VeranoController@modificar2')
    ->name('verano_modificar2');
Route::get('/verano/grupos/modificar/{materia}/{gpo}','VeranoController@modificar3')
    ->name('verano_modificar3')
    ->middleware('auth','role:verano');
Route::post('/verano/grupos/modificar/horario','VeranoController@updatehorario')
    ->name('verano_grupo_modifica')->middleware('auth','role:verano');
Route::get('/verano/alumnos/consulta','VeranoController@buscar')
    ->middleware('auth','role:verano');
Route::post('/verano/alumno/buscar','VeranoController@busqueda')
    ->name('verano.buscar')
    ->middleware('auth','role:verano');
Route::post('/verano/alumno/datos','VeranoController@accion2')
    ->name('verano.accion2')
    ->middleware('auth','role:verano');
Route::get('/verano/estadistica/poblacion','VeranoController@poblacion')
    ->middleware('auth','role:verano');
Route::get('/verano/estadistica/{carrera}/{reticula}','VeranoController@pobxcarrera')
    ->name('verano_est_carrera')
    ->middleware('auth','role:verano');
Route::get('/verano/estadistica/aulas','VeranoController@pobxaulas')
    ->middleware('auth','role:verano');
Route::post('/verano/estadistico/aula2','VeranoController@pobxaulas2')
    ->name('verano_aula')
    ->middleware('auth','role:verano');
//AQUI TERMINA COORD VERANO

//AQUI COMIENZA PLANEACION
Route::get('/planeacion', 'PlaneacionController@index')
    ->name('inicio_planeacion')
    ->middleware('auth','role:planeacion');
Route::get('/planeacion/estadistica/prepoblacion','PlaneacionController@prepoblacion')
    ->middleware('auth','role:planeacion');
Route::get('/planeacion/estadistica/preedades','PlaneacionController@preedades')
    ->middleware('auth','role:planeacion');
Route::get('/planeacion/estadistica/preedadesc','PlaneacionController@preedadesc')
    ->middleware('auth','role:planeacion');
Route::get('/planeacion/estadistica/preedadesedo','PlaneacionController@preedadesedo')
    ->middleware('auth','role:planeacion');
Route::post('/planeacion/estadistica/poblacion','PlaneacionController@poblacion')
    ->name('planeacion.poblacion')
    ->middleware('auth','role:planeacion');
Route::post('/planeacion/estadistica/edades','PlaneacionController@edades')
    ->name('planeacion.edades')
    ->middleware('auth','role:planeacion');
Route::post('/planeacion/estadistica/edades_carrera','PlaneacionController@edadesc')
    ->name('planeacion.edadesc')
    ->middleware('auth','role:planeacion');
Route::post('/planeacion/estadistica/edades_estado','PlaneacionController@edadesedo')
    ->name('planeacion.edadesedo')
    ->middleware('auth','role:planeacion');
Route::get('/planeacion/estadistica/{periodo}/{carrera}/{reticula}','PlaneacionController@pobxcarrera')
    ->name('planeacion.est_carrera')
    ->middleware('auth','role:planeacion');
Route::get('/planeacion/estadistica/preegreso','PlaneacionController@preegreso')
    ->middleware('auth','role:planeacion');
Route::get('/planeacion/estadistica/preegreso2','PlaneacionController@preegreso2')
    ->middleware('auth','role:planeacion');
Route::post('/planeacion/estadistica/consulta_egreso','PlaneacionController@egreso')
    ->name('planeacion.egreso')
    ->middleware('auth','role:planeacion');
Route::post('/planeacion/estadistica/consulta_egreso2','PlaneacionController@egreso2')
    ->name('planeacion.egreso_completo')
    ->middleware('auth','role:planeacion');
Route::get('/planeacion/carreras/materias','PlaneacionController@materianueva')
    ->middleware('auth','role:planeacion');
Route::post('/planeacion/materias/accion','PlaneacionController@materiasacciones')
    ->name('planeacion.materias_acciones');
Route::post('/planeacion/reticulas/vista','PlaneacionController@vistareticula')
    ->name('planeacion.vista_reticula')
    ->middleware('auth','role:planeacion');
Route::get('/planeacion/contrasena','PlaneacionController@contrasenia')
    ->middleware('auth','role:planeacion');
Route::post('/planeacion/ccontrasena','PlaneacionController@ccontrasenia')
    ->name('planeacion.contra')
    ->middleware('auth','role:planeacion');
//AQUI TERMINA PLANEACION
